### ISSUE TITLE
this plugin have no effect

### ISSUE THREAD

**Issue by how2051** [viduycheung/dida-obsidian#1]
Hi, I follow your advice and clone this repo, build it as [this](https://docs.obsidian.md/Plugins/Getting+started/Build+a+plugin#Step+2+Build+the+plugin) mentions, and manually install it as [this](https://github.com/obsidianmd/obsidian-sample-plugin#manually-installing-the-plugin) mentions.

And then I got the API token

but when I use the command, it doesn't work, it has no effect
![图片](https://github.com/viduycheung/dida-obsidian/assets/55384174/65d6845b-1304-45ef-b9a4-e63dc1076448)
I create a new md to use the command, click to create task, no any effect

![图片](https://github.com/viduycheung/dida-obsidian/assets/55384174/219a1522-e089-493e-9e6e-7b0810be1436)
I use the command to fetch data, it shows success but still, nothing happen in my md file

Is there some things I miss, or what else I could do to use this plugin?

**Comment by viduycheung** [comment]
You can check the task you create in TickTick.

Here is the usage of current commands
- New Task (Create Task to TickTick with your selection or open file)
- Fetch Data (Muaunly fetch the data that the `New Task` needs, like your projects in your TickTick)

**Comment by how2051** [comment]
oh, so it will not create in Dida, right? 
I've try `New Task` so many times, and I go to my Dida APP to check, no new task is created.
The same as `Fetch Data`

**Comment by viduycheung** [comment]
Sorry about the confusion, I mean Dida actually.
I record a video, if you see the 'Add xxx' toast after creating a task, it means you create a task success. You go to the web/app to click the sync button to sync the task you created.

https://github.com/viduycheung/dida-obsidian/assets/53415256/c9e7e1bb-859d-4323-a242-20a693801df4

**Comment by how2051** [comment]
I do the same thing, but no 'Add xxx' toast after creating a task, nothing shown on the topright.
here's my record:

https://github.com/viduycheung/dida-obsidian/assets/55384174/aba6da64-5fdc-4136-b4f3-1dffaf6b944c

Since this Dida plugin is installed manually, will I miss somet steps or something?

**Comment by viduycheung** [comment]
视频看不到画面，我觉的你可以试试看换个网络环境试试~
创建任务的请求成功的话会有 `Add ${taskData.title}` 的 Toast，失败则是 `Add Failed`，如果是 token 不合法的话会有 `Your ${productName} login credentials have expired. Please login again.` 的 Toast

**Comment by how2051** [comment]
https://github.com/viduycheung/dida-obsidian/assets/55384174/05d75143-4daa-4406-9f0d-302668118b7f

我重新发了个视频，你看看。
我在创建任务的时候右上角没有任何提示信息，也没报错也没提示成功，就好像什么效果都没有。
我在sync的时候右上角会提示成功，但文件里面也是什么都没有。

**Comment by viduycheung** [comment]
![CleanShot 2023-11-27 at 12  00 28@2x](https://github.com/viduycheung/dida-obsidian/assets/53415256/c7d85739-c6e9-4d0c-a9d1-ccb54ffac6b9)
![CleanShot 2023-11-27 at 12  00 13@2x](https://github.com/viduycheung/dida-obsidian/assets/53415256/e4e37c8f-c54e-4bf5-bab8-75a696fe6f08)

你切出开发者工具，这处代码中加个 log，用 `npm run dev` 运行起来之后在 Obsidian 中将插件刷新一下，然后尝试添加一次，打出来的 log 发我看下

**Comment by how2051** [comment]
晚上好，我按照你的提示做了相关操作，结果如下：

我更改了main.ts，加了一些log，重新编译重新安装并且在 obsidian 中更新了插件，
你要的data打印不出来，打印结果为 `undefined`
![7be41df94c49c47d3a0e0f93220a46d](https://github.com/viduycheung/dida-obsidian/assets/55384174/042bf650-8415-4583-b6bf-164f98285619)

更进一步地，我做了下面这些尝试，可能能够帮你快速定位问题：
我怀疑是请求失败导致data为空，所以才我在请求里面增加了一些log，如下：
![图片](https://github.com/viduycheung/dida-obsidian/assets/55384174/fe2da3db-beaa-4222-bb6a-cced0f95ee32)

刷新插件之后，我在obsidian中再次创建task时，报错 500：
![图片](https://github.com/viduycheung/dida-obsidian/assets/55384174/77c81889-f9fa-4d26-a65b-b55d9a90fca7)


我在想这会不会是和滴答本身的服务器相关了，到这里我就没法再跟进了。

**Comment by viduycheung** [comment]
好的，感觉像是接口的问题，你那里有 Postman 这样的工具吗？可以试试访问这个 API，将 headers 中的 Authorization 设置成 Bearer [token], 看看这个接口的返回结果是什么
![CleanShot 2023-11-28 at 9  22 28@2x](https://github.com/viduycheung/dida-obsidian/assets/53415256/ef3c2da9-22ac-455e-a9a9-d17e2d85b5df)

**Comment by how2051** [comment]
晚上好，我用RESTClient访问了这个API，看样子API本身是没问题的，相关截图如下：
![QQ截图20231128225503](https://github.com/viduycheung/dida-obsidian/assets/55384174/aaf95ca3-b887-4878-a6f8-aa2ce826bee7)
![QQ截图20231128225558](https://github.com/viduycheung/dida-obsidian/assets/55384174/c5b75721-dcf2-4d0e-a3bb-df92ca735c7c)

**Comment by how2051** [comment]
我用滴答清单网页版看了一下创建任务时的HTTP请求，用Python写了个简单的脚本模拟了一下，可以实现创建Task，FYI
```python
import requests

url = "https://api.dida365.com/api/v2/batch/task"
# url = "https://api.dida365.com/open/v1/task"

headers = {
    # "Authorization": "Bearer xxxx",
    "Cookie": "t=xxxxx; oai=xxxx; AWSALB=xxxx; AWSALBCORS=xxxx; SESSION=xxxx; tt_distid=help-xxxx",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0",
}


from datetime import datetime, timezone

def create_task(title, content):
    current_time = datetime.utcnow().replace(tzinfo=timezone.utc)
    current_time_str = current_time.strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"

    task_data = {
        "add": [
            {
                "assignee": None,
                "content": content,
                "createdTime": current_time_str,
                "dueDate": None,
                "exDate": [],
                "id": str(current_time.timestamp()), #"2023-11-28T23:24:06.000+0000"
                "isAllDay": True,
                "isFloating": False,
                "items": [],
                "kind": None,
                "modifiedTime": current_time_str,
                "priority": 0,
                "progress": 0,
                "projectId": "inbox1011896344",
                "reminders": [],
                "sortOrder": -1533295546269696,
                "startDate": current_time_str,
                "status": 0,
                "tags": [],
                "timeZone": "Asia/Shanghai",
                "title": title
            }
        ],
        "addAttachments": [],
        "delete": [],
        "deleteAttachments": [],
        "update": [],
        "updateAttachments": []
    }

    return task_data

# 示例使用
title_input = "Your Title"
content_input = "Your Content"

task_data = create_task(title_input, content_input)
# print(task_data)



try:
    response = requests.post(url, json=task_data, headers=headers)
    response.raise_for_status()

    print(response.status_code)
    try:
        json_response = response.json()
        print(json_response)
    except requests.exceptions.JSONDecodeError:
        print("Response is not a valid JSON:", response.text)

except requests.exceptions.HTTPError as errh:
    print("HTTP Error:", errh)

except requests.exceptions.RequestException as err:
    print("Request Error:", err)
    print(response.text)

```

不过我看网页版采用的是 `api/v2/batch/task` 而不是 `open/v1/task`，后者我用了发现会报error。
另外，网页版并没有采用 `Authorization` 接收 token，而是采用 `Cookie`。

希望这些信息能够帮到你~

**Comment by viduycheung** [comment]
我重新提交了代码 https://github.com/viduycheung/dida-obsidian/commit/21b0f7470eebbabe5fcfc8df7c08a606813e240a ， 你可以再试试看，之前的代码没有处理没有任何返回的请求（比如网络断开）。比如 Fetch data 命令会直接认为请求结束提示成功，New task 命令会没有任何提示。

如果新的代码在请求后出现了错误的 toast， 可以在 console 中看到对应请求失败的原因。

**Comment by viduycheung** [comment]
> 我用滴答清单网页版看了一下创建任务时的HTTP请求，用Python写了个简单的脚本模拟了一下，可以实现创建Task，FYI
> 
> ```python
> import requests
> 
> url = "https://api.dida365.com/api/v2/batch/task"
> # url = "https://api.dida365.com/open/v1/task"
> 
> headers = {
>     # "Authorization": "Bearer xxxx",
>     "Cookie": "t=xxxxx; oai=xxxx; AWSALB=xxxx; AWSALBCORS=xxxx; SESSION=xxxx; tt_distid=help-xxxx",
>     "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0",
> }
> 
> 
> from datetime import datetime, timezone
> 
> def create_task(title, content):
>     current_time = datetime.utcnow().replace(tzinfo=timezone.utc)
>     current_time_str = current_time.strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"
> 
>     task_data = {
>         "add": [
>             {
>                 "assignee": None,
>                 "content": content,
>                 "createdTime": current_time_str,
>                 "dueDate": None,
>                 "exDate": [],
>                 "id": str(current_time.timestamp()), #"2023-11-28T23:24:06.000+0000"
>                 "isAllDay": True,
>                 "isFloating": False,
>                 "items": [],
>                 "kind": None,
>                 "modifiedTime": current_time_str,
>                 "priority": 0,
>                 "progress": 0,
>                 "projectId": "inbox1011896344",
>                 "reminders": [],
>                 "sortOrder": -1533295546269696,
>                 "startDate": current_time_str,
>                 "status": 0,
>                 "tags": [],
>                 "timeZone": "Asia/Shanghai",
>                 "title": title
>             }
>         ],
>         "addAttachments": [],
>         "delete": [],
>         "deleteAttachments": [],
>         "update": [],
>         "updateAttachments": []
>     }
> 
>     return task_data
> 
> # 示例使用
> title_input = "Your Title"
> content_input = "Your Content"
> 
> task_data = create_task(title_input, content_input)
> # print(task_data)
> 
> 
> 
> try:
>     response = requests.post(url, json=task_data, headers=headers)
>     response.raise_for_status()
> 
>     print(response.status_code)
>     try:
>         json_response = response.json()
>         print(json_response)
>     except requests.exceptions.JSONDecodeError:
>         print("Response is not a valid JSON:", response.text)
> 
> except requests.exceptions.HTTPError as errh:
>     print("HTTP Error:", errh)
> 
> except requests.exceptions.RequestException as err:
>     print("Request Error:", err)
>     print(response.text)
> ```
> 
> 不过我看网页版采用的是 `api/v2/batch/task` 而不是 `open/v1/task`，后者我用了发现会报error。 另外，网页版并没有采用 `Authorization` 接收 token，而是采用 `Cookie`。
> 
> 希望这些信息能够帮到你~

当前插件使用的是 openAPI 走的是 oauth 验证的流程， openAPI 有一套独立的接口 https://developer.dida365.com/docs#/openapi ，开发者并不能随意操作数据且用户可以在设置关联应用中进行管理。网页的 cookie 是通过用户的账户密码登陆后生成的，且有了 cookie 后可以调用任意接口操作用户数据，是不安全的。

**Comment by how2051** [comment]
好的，我用cookies的那种方式确实不妥，纯纯的野路子，都是靠自己一次一次瞎试出来的。:)
公司电脑上我没装相应的环境，我今晚下班回去再更新代码重新试一下，有问题再给你反馈。

**Comment by how2051** [comment]
晚上好，以下是今晚的一些尝试和结果：

更新了代码重新编译安装之后，会有新toast出现，提示添加task失败。
打开开发者工具，在console中看到相应的报错如下：
![QQ截图20231129224010](https://github.com/viduycheung/dida-obsidian/assets/55384174/90f858b9-8502-4a43-a58d-929e61ba658b)

fetch data则是老样子，toast提示成功，但没看到有什么变化。

以上现象的录屏如下：

https://github.com/viduycheung/dida-obsidian/assets/55384174/3ccb3da4-1dc6-4cda-a796-b1146b6f5d82

另外，我把error log也保存下来了，见附件：
[obsidian.md-1701268682237.log](https://github.com/viduycheung/dida-obsidian/files/13501867/obsidian.md-1701268682237.log)

**Comment by viduycheung** [comment]
好的，你到 https://dida365.com/webapp (登陆和 obsidian 相同的账号）点击左下角「？」- 「反馈与建议」提交一个反馈，说明一下是 obsidian 插件接口调用 500，我让我们同事帮你查下是什么问题

**Comment by how2051** [comment]
好的，已提交反馈。感谢~

**Comment by viduycheung** [comment]
Oauth 获取的权限不对导致的接口失败，可以再拉一遍代码，然后将设置中的 token 清空，重新认证（确认下授权的页面是否有图中表示的这一条权限）一遍填入新的 token。
![CleanShot 2023-11-30 at 2  31 04@2x](https://github.com/viduycheung/dida-obsidian/assets/53415256/5ca4632e-47cb-45f7-a671-01cedf3220c1)

**Comment by how2051** [comment]
最新版本已经可以创造任务啦~

最开始那个token确实没有写权限
![691898374d8623ce0c420213750c881](https://github.com/viduycheung/dida-obsidian/assets/55384174/47c38253-fb5e-4f5f-b1a6-eb64913405e2)


后面的就有了：
![4ce9a69d695d78fbcaba5a982b7a37b](https://github.com/viduycheung/dida-obsidian/assets/55384174/84cbc386-4a07-48c3-a032-8fd8ace5386c)

感谢这些天的耐心回复，感谢~

**Comment by how2051** [comment]
不过那个Fetch user data的指令的效果是咋样的，目前我这边好像看起来还是没有效果。
我先把这个issue关了吧，如果你觉得有必要我再重新开个issue跟进那个问题

**Comment by viduycheung** [comment]
> 不过那个Fetch user data的指令的效果是咋样的，目前我这边好像看起来还是没有效果。
> 
> 我先把这个issue关了吧，如果你觉得有必要我再重新开个issue跟进那个问题

那个其实是成功的，在添加任务中你可以选择清单，这个数据我有做自动的同步逻辑，但是并不能保证永远是最新的，所以增加了一个指令可以让用户手动拉取数据。比如你新建了一个清单，可能第一时间无法在创建任务弹窗中选择，这时候可以手动拉取来获取到这个清单的数据

**Comment by how2051** [comment]
> > 不过那个Fetch user data的指令的效果是咋样的，目前我这边好像看起来还是没有效果。
> > 我先把这个issue关了吧，如果你觉得有必要我再重新开个issue跟进那个问题
> 
> 那个其实是成功的，在添加任务中你可以选择清单，这个数据我有做自动的同步逻辑，但是并不能保证永远是最新的，所以增加了一个指令可以让用户手动拉取数据。比如你新建了一个清单，可能第一时间无法在创建任务弹窗中选择，这时候可以手动拉取来获取到这个清单的数据

soga，你不说我都还不知道有“清单”这么个功能，从来没用过。刚才试了一下，确实可以的。/点赞

**Comment by how2051** [comment]
话说看样子我应该是这个插件的第一个用户，嘿嘿~
